export const INITIAL_MEDIA_LIST = [
  {
    id: "media_001",
    title: "Thử nghiệm xe buýt tự hành Xbus tuyến nội bộ",
    fileName: "xbus_autonomous_road_test_2026.mp4",
    type: "video",
    url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    thumbnail: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80",
    fileSize: 45200000,
    fileSizeFormatted: "43.1 MB",
    fileFormat: "MP4",
    dimensions: "3840 x 2160 (4K)",
    duration: "03:45",
    durationSeconds: 225,
    uploadedAt: "2026-09-28T10:15:00Z",
    uploader: {
      id: "usr_001",
      name: "Vũ Hoàng Dũng",
      email: "dungvh@phenikaa-x.com",
      code: "PNKX047",
      avatar: "/images/avatars/male-admin.png",
      role: "Quản Lý Dự Án",
      department: "Quản Lý Dự Án",
    },
    privacy: "public",
    tags: ["#xe_tuhanh", "#road_test", "#xbus", "#ap"],
    description:
      "Video ghi lại hành trình vận hành tự động cấp độ 4 của xe buýt Xbus tại khu công nghệ cao, tự động nhận diện làn đường, tránh người đi bộ và dừng đỗ đón trả khách chính xác.",
    likes: 24,
    isLiked: false,
    exif: {
      camera: "Sony Alpha A7 IV + FE 24-70mm GM II",
      resolution: "4K UHD (3840 x 2160)",
      fps: "60 fps",
      bitrate: "45 Mbps",
      codec: "H.264 / AAC",
    },
    comments: [
      {
        id: "cmt_1",
        author: {
          name: "Hà Quốc Việt",
          avatar: "/images/avatars/male-user.png",
          department: "AP",
        },
        content: "Độ mượt khi phanh ở các khúc cua gấp cải thiện rất nhiều so với bản test tuần trước anh Dũng ơi!",
        createdAt: "2026-09-28T11:20:00Z",
      },
      {
        id: "cmt_2",
        author: {
          name: "Nguyễn Thị Hồng Quyên",
          avatar: "/images/avatars/female-user.png",
          department: "Web App",
        },
        content: "Đã đồng bộ dữ liệu telemetry từ chuyến chạy này lên Dashboard trung tâm rồi ạ.",
        createdAt: "2026-09-28T12:05:00Z",
      },
    ],
  },
  {
    id: "media_002",
    title: "Hiệu chỉnh cụm cảm biến LiDAR và Camera nóc xe",
    fileName: "xbus_lidar_sensor_setup.jpg",
    type: "image",
    url: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1600&q=80",
    thumbnail: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80",
    fileSize: 6800000,
    fileSizeFormatted: "6.5 MB",
    fileFormat: "JPG",
    dimensions: "4032 x 3024",
    uploadedAt: "2026-09-28T08:30:00Z",
    uploader: {
      id: "usr_002",
      name: "Hà Quốc Việt",
      email: "viethq@phenikaa-x.com",
      code: "PNKX019",
      avatar: "/images/avatars/male-user.png",
      role: "Kỹ sư AP",
      department: "AP",
    },
    privacy: "team",
    tags: ["#sensor", "#lidar", "#calibration", "#ap"],
    description:
      "Ảnh chụp quy trình căn chỉnh và đồng bộ thời gian (time-sync) giữa cụm 3 cảm biến LiDAR 64 tia và 6 camera góc rộng trên giá nóc xe Xbus trước khi xuất xưởng.",
    likes: 15,
    isLiked: true,
    exif: {
      camera: "Canon EOS R5 + RF 50mm f/1.2L",
      resolution: "4032 x 3024 (12 MP)",
      lens: "50mm, f/2.8, 1/250s",
      iso: "ISO 400",
      colorSpace: "sRGB",
    },
    comments: [
      {
        id: "cmt_3",
        author: {
          name: "Vũ Hoàng Dũng",
          avatar: "/images/avatars/male-admin.png",
          department: "Quản Lý Dự Án",
        },
        content: "Cân chỉnh rất chuẩn, độ lệch sai số góc chiếu dưới 0.05 độ theo đúng tiêu chuẩn thiết kế.",
        createdAt: "2026-09-28T09:10:00Z",
      },
    ],
  },
  {
    id: "media_003",
    title: "Teambuilding Xbus gắn kết tại Ba Vì",
    fileName: "teambuilding_ba_vi_autumn_2026.jpg",
    type: "image",
    url: "https://images.unsplash.com/photo-1511632765486-a01980e01a18?auto=format&fit=crop&w=1600&q=80",
    thumbnail: "https://images.unsplash.com/photo-1511632765486-a01980e01a18?auto=format&fit=crop&w=800&q=80",
    fileSize: 8400000,
    fileSizeFormatted: "8.0 MB",
    fileFormat: "JPG",
    dimensions: "5472 x 3648",
    uploadedAt: "2026-09-27T15:45:00Z",
    uploader: {
      id: "usr_007",
      name: "Nguyễn Thị Hồng Quyên",
      email: "quyennth@phenikaa-x.com",
      code: "PNKX281",
      avatar: "/images/avatars/female-user.png",
      role: "Trợ lý Văn phòng",
      department: "Web App",
    },
    privacy: "public",
    tags: ["#teambuilding", "#sukien", "#xbus_family", "#bavi"],
    description:
      "Khoảnh khắc toàn thể anh em kỹ sư, nhân sự phòng AP, Web App và Vận Hành Xbus cùng chụp ảnh lưu niệm sau chuỗi hoạt động dã ngoại tại Ba Vì.",
    likes: 42,
    isLiked: true,
    exif: {
      camera: "Fujifilm X-T4 + XF 16-55mm f/2.8",
      resolution: "5472 x 3648 (20 MP)",
      lens: "24mm, f/4.0, 1/500s",
      iso: "ISO 160",
      colorSpace: "Adobe RGB",
    },
    comments: [
      {
        id: "cmt_4",
        author: {
          name: "Hoàng Duy Lộc",
          avatar: "/images/avatars/male-user.png",
          department: "AP",
        },
        content: "Chuyến đi quá vui và ý nghĩa! Cảm ơn chị Quyên đã chuẩn bị hậu cần chu đáo ❤️",
        createdAt: "2026-09-27T16:30:00Z",
      },
    ],
  },
  {
    id: "media_004",
    title: "Mô phỏng thuật toán lập quỹ đạo di chuyển (Motion Planning)",
    fileName: "simulator_motion_planning_demo.mp4",
    type: "video",
    url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    thumbnail: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80",
    fileSize: 89000000,
    fileSizeFormatted: "84.9 MB",
    fileFormat: "MP4",
    dimensions: "1920 x 1080",
    duration: "04:12",
    durationSeconds: 252,
    uploadedAt: "2026-09-26T14:10:00Z",
    uploader: {
      id: "usr_003",
      name: "Hoàng Duy Lộc",
      email: "lochd@phenikaa-x.com",
      code: "PNKX029",
      avatar: "/images/avatars/male-user.png",
      role: "Kỹ sư AP",
      department: "AP",
    },
    privacy: "team",
    tags: ["#simulation", "#planning", "#algorithm", "#ap"],
    description:
      "Video demo trên môi trường mô phỏng CARLA Simulator kết hợp ROS2, kiểm tra tính ổn định của thuật toán Lattice Planning trong kịch bản xe gặp vật cản bất ngờ.",
    likes: 19,
    isLiked: false,
    exif: {
      camera: "Screen Recording (OBS Studio NVENC)",
      resolution: "1920 x 1080 (Full HD)",
      fps: "60 fps",
      bitrate: "30 Mbps",
      codec: "H.265 / HEVC",
    },
    comments: [],
  },
  {
    id: "media_005",
    title: "Tiệc trà chiều thứ Sáu chào đón thành viên mới",
    fileName: "happy_hour_tea_break_friday.jpg",
    type: "image",
    url: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1600&q=80",
    thumbnail: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80",
    fileSize: 5200000,
    fileSizeFormatted: "5.0 MB",
    fileFormat: "JPG",
    dimensions: "4000 x 3000",
    uploadedAt: "2026-09-25T16:30:00Z",
    uploader: {
      id: "usr_007",
      name: "Nguyễn Thị Hồng Quyên",
      email: "quyennth@phenikaa-x.com",
      code: "PNKX281",
      avatar: "/images/avatars/female-user.png",
      role: "Trợ lý Văn phòng",
      department: "Web App",
    },
    privacy: "public",
    tags: ["#trachieu", "#happyhour", "#vanphong", "#fun"],
    description:
      "Bàn tiệc trà chiều tuần này có trà đào cam sả, hoa quả tươi và bánh ngọt để tiếp năng lượng cho anh em sau giờ làm việc căng thẳng.",
    likes: 31,
    isLiked: false,
    exif: {
      camera: "iPhone 15 Pro Max",
      resolution: "4000 x 3000 (12 MP)",
      lens: "24mm f/1.78",
      iso: "ISO 125",
      colorSpace: "Display P3",
    },
    comments: [
      {
        id: "cmt_5",
        author: {
          name: "Bùi Văn Quốc Anh",
          avatar: "/images/avatars/male-user.png",
          department: "Web App",
        },
        content: "Trà đào hôm nay ngon tuyệt vời chị Quyên ơi!",
        createdAt: "2026-09-25T16:45:00Z",
      },
    ],
  },
  {
    id: "media_006",
    title: "Khoang nội thất xe Xbus thế hệ mới với màn hình thông minh",
    fileName: "xbus_cabin_interior_display.jpg",
    type: "image",
    url: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1600&q=80",
    thumbnail: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80",
    fileSize: 7300000,
    fileSizeFormatted: "7.0 MB",
    fileFormat: "JPG",
    dimensions: "4500 x 3000",
    uploadedAt: "2026-09-24T11:00:00Z",
    uploader: {
      id: "usr_004",
      name: "Nguyễn Trung Kiên",
      email: "kiennt@phenikaa-x.com",
      code: "PNKX062",
      avatar: "/images/avatars/male-user.png",
      role: "Kỹ sư AP",
      department: "AP",
    },
    privacy: "public",
    tags: ["#interior", "#display", "#smart_cabin", "#xbus"],
    description:
      "Bố trí khoang hành khách 12 chỗ ngồi hiện đại, trang bị màn hình giải trí tương tác hiển thị trực quan bản đồ hành trình và camera quan sát thời gian thực.",
    likes: 27,
    isLiked: true,
    exif: {
      camera: "Nikon Z7 II + NIKKOR Z 24-70mm f/2.8 S",
      resolution: "4500 x 3000",
      lens: "35mm, f/4.0, 1/160s",
      iso: "ISO 250",
      colorSpace: "sRGB",
    },
    comments: [],
  },
  {
    id: "media_007",
    title: "Workshop chia sẻ kỹ thuật Edge AI Computing trên Jetson Orin",
    fileName: "workshop_ai_edge_computing.jpg",
    type: "image",
    url: "https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=1600&q=80",
    thumbnail: "https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=800&q=80",
    fileSize: 4900000,
    fileSizeFormatted: "4.7 MB",
    fileFormat: "JPG",
    dimensions: "3840 x 2560",
    uploadedAt: "2026-09-22T09:30:00Z",
    uploader: {
      id: "usr_005",
      name: "Trần Cao Khâm",
      email: "khamtc@phenikaa-x.com",
      code: "PNKX170",
      avatar: "/images/avatars/male-user.png",
      role: "Kỹ sư AP",
      department: "AP",
    },
    privacy: "team",
    tags: ["#workshop", "#edge_ai", "#nvidia_orin", "#training"],
    description:
      "Tài liệu hình ảnh buổi đào tạo nội bộ về tối ưu hóa mô hình mạng nơ-ron nhận diện vật cản sử dụng TensorRT 10.x trên máy tính điều khiển nhúng xe Xbus.",
    likes: 29,
    isLiked: false,
    exif: {
      camera: "Sony Alpha A7 IV",
      resolution: "3840 x 2560",
      lens: "35mm, f/2.0, 1/200s",
      iso: "ISO 800",
      colorSpace: "sRGB",
    },
    comments: [],
  },
  {
    id: "media_008",
    title: "Trạm sạc tự động thông minh chuẩn kết nối CCS2 cho Xbus",
    fileName: "xbus_smart_charging_station.mp4",
    type: "video",
    url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    thumbnail: "https://images.unsplash.com/photo-1558441719-8b489c63f771?auto=format&fit=crop&w=800&q=80",
    fileSize: 62000000,
    fileSizeFormatted: "59.1 MB",
    fileFormat: "MP4",
    dimensions: "1920 x 1080",
    duration: "02:15",
    durationSeconds: 135,
    uploadedAt: "2026-09-20T14:20:00Z",
    uploader: {
      id: "usr_009",
      name: "Bùi Đình Quý",
      email: "quybd@phenikaa-x.com",
      code: "PNKX296",
      avatar: "/images/avatars/male-user.png",
      role: "Kỹ sư Vận Hành",
      department: "Vận Hành",
    },
    privacy: "public",
    tags: ["#charging", "#ev", "#smart_station", "#van_hanh"],
    description:
      "Clip ghi lại cơ chế xe tự động lùi vào chuồng sạc và cánh tay robot tự động cắm đầu sạc công suất 120kW, tối ưu thời gian vận hành cho đội xe.",
    likes: 38,
    isLiked: false,
    exif: {
      camera: "Panasonic Lumix GH6 + 12-60mm Leica",
      resolution: "1920 x 1080 (60 fps)",
      bitrate: "50 Mbps",
      codec: "ProRes / H.264",
    },
    comments: [],
  },
  {
    id: "media_009",
    title: "Kiểm thử camera ban đêm và nhận diện chướng ngại vật",
    fileName: "xbus_night_drive_camera_benchmark.jpg",
    type: "image",
    url: "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?auto=format&fit=crop&w=1600&q=80",
    thumbnail: "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?auto=format&fit=crop&w=800&q=80",
    fileSize: 7800000,
    fileSizeFormatted: "7.4 MB",
    fileFormat: "JPG",
    dimensions: "4200 x 2800",
    uploadedAt: "2026-09-18T21:40:00Z",
    uploader: {
      id: "usr_006",
      name: "Trần Hoàng Hà",
      email: "hath@phenikaa-x.com",
      code: "PNKX335",
      avatar: "/images/avatars/male-user.png",
      role: "Kỹ sư AP",
      department: "AP",
    },
    privacy: "team",
    tags: ["#night_drive", "#benchmark", "#low_light", "#ap"],
    description:
      "Kết quả độ chính xác nhận diện người đi bộ và xe máy trong điều kiện ánh sáng yếu dưới 5 lux. Model AI đạt độ tin cậy trên 96.8% ở khoảng cách 60m.",
    likes: 21,
    isLiked: false,
    exif: {
      camera: "Sony FX3 + 24mm f/1.4 GM",
      resolution: "4200 x 2800",
      lens: "24mm, f/1.4, 1/60s",
      iso: "ISO 3200",
      colorSpace: "sRGB",
    },
    comments: [],
  },
  {
    id: "media_010",
    title: "Lễ vinh danh sáng kiến kỹ thuật xuất sắc tháng",
    fileName: "xbus_team_awarding_ceremony.jpg",
    type: "image",
    url: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1600&q=80",
    thumbnail: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=800&q=80",
    fileSize: 6100000,
    fileSizeFormatted: "5.8 MB",
    fileFormat: "JPG",
    dimensions: "3600 x 2400",
    uploadedAt: "2026-09-15T10:00:00Z",
    uploader: {
      id: "usr_001",
      name: "Vũ Hoàng Dũng",
      email: "dungvh@phenikaa-x.com",
      code: "PNKX047",
      avatar: "/images/avatars/male-admin.png",
      role: "Quản Lý Dự Án",
      department: "Quản Lý Dự Án",
    },
    privacy: "public",
    tags: ["#award", "#vinhdanh", "#sangtao", "#xbus_team"],
    description:
      "Trao bằng khen và phần thưởng cho nhóm nghiên cứu hệ thống điều hướng bản đồ độ nét cao HD Map và thuật toán định vị GNSS/IMU Fusion.",
    likes: 47,
    isLiked: true,
    exif: {
      camera: "Fujifilm X-T4",
      resolution: "3600 x 2400",
      lens: "35mm, f/2.8, 1/250s",
      iso: "ISO 400",
      colorSpace: "sRGB",
    },
    comments: [],
  },
  {
    id: "media_011",
    title: "Kiểm tra khung gầm và hệ thống lái trợ lực điện Steer-by-Wire",
    fileName: "chassis_steer_by_wire_inspection.jpg",
    type: "image",
    url: "https://images.unsplash.com/photo-1486006920555-c77dce18193b?auto=format&fit=crop&w=1600&q=80",
    thumbnail: "https://images.unsplash.com/photo-1486006920555-c77dce18193b?auto=format&fit=crop&w=800&q=80",
    fileSize: 7200000,
    fileSizeFormatted: "6.9 MB",
    fileFormat: "JPG",
    dimensions: "4000 x 2667",
    uploadedAt: "2026-09-12T14:30:00Z",
    uploader: {
      id: "usr_010",
      name: "Bùi Văn Quốc Anh",
      email: "anhbvq@phenikaa-x.com",
      code: "PNKX304",
      avatar: "/images/avatars/male-user.png",
      role: "Kỹ sư Web App",
      department: "Web App",
    },
    privacy: "private",
    tags: ["#chassis", "#steer_by_wire", "#mechanical", "#safety"],
    description:
      "Hệ thống dự phòng kép (dual redundancy) của bộ truyền động đánh lái điện tử, đảm bảo xe vẫn kiểm soát an toàn 100% trong mọi tình huống lỗi đơn lẻ.",
    likes: 18,
    isLiked: false,
    exif: {
      camera: "Canon EOS R6 Mark II",
      resolution: "4000 x 2667",
      lens: "24-105mm, f/4.0",
      iso: "ISO 640",
      colorSpace: "sRGB",
    },
    comments: [],
  },
  {
    id: "media_012",
    title: "Phát hành bản cập nhật phần mềm Xbus OS v4.0",
    fileName: "software_release_v4_celebration.jpg",
    type: "image",
    url: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=1600&q=80",
    thumbnail: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=800&q=80",
    fileSize: 5800000,
    fileSizeFormatted: "5.5 MB",
    fileFormat: "JPG",
    dimensions: "3840 x 2560",
    uploadedAt: "2026-09-08T17:00:00Z",
    uploader: {
      id: "usr_001",
      name: "Vũ Hoàng Dũng",
      email: "dungvh@phenikaa-x.com",
      code: "PNKX047",
      avatar: "/images/avatars/male-admin.png",
      role: "Quản Lý Dự Án",
      department: "Quản Lý Dự Án",
    },
    privacy: "public",
    tags: ["#release", "#xbus_os", "#software", "#milestone"],
    description:
      "Cột mốc quan trọng đánh dấu bản Xbus OS v4.0 hoàn tất kiểm thử 10.000 km thực tế không xảy ra sự cố can thiệp của tài xế.",
    likes: 56,
    isLiked: true,
    exif: {
      camera: "Sony Alpha A7 IV",
      resolution: "3840 x 2560",
      lens: "28mm, f/2.8, 1/125s",
      iso: "ISO 500",
      colorSpace: "sRGB",
    },
    comments: [
      {
        id: "cmt_6",
        author: {
          name: "Lê Tuấn Long",
          avatar: "/images/avatars/male-user.png",
          department: "AP",
        },
        content: "Chúc mừng cả team AP & Web App đã nỗ lực hết mình suốt quý vừa rồi!",
        createdAt: "2026-09-08T17:30:00Z",
      },
    ],
  },
];

export const POPULAR_TAGS = [
  "#xe_tuhanh",
  "#road_test",
  "#sensor",
  "#lidar",
  "#teambuilding",
  "#sukien",
  "#trachieu",
  "#vanphong",
  "#workshop",
  "#ap",
  "#planning",
  "#xbus",
];
